export const FETCH_COLLECTIONS = "FETCH_COLLECTIONS";
export const FETCH_FAVORITE_COLLECTIONS = "FETCH_FAVORITE_COLLECTIONS";
export const ADD_FAVORITE_COLLECTION = "ADD_FAVORITE_COLLECTION";
export const DELETE_FAVORITE_COLLECTION = "DELETE_FAVORITE_COLLECTION";
export const SEARCH_COLLECTIONS = "SEARCH_COLLECTIONS";